### ISSUE TITLE
Comparing two test results

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#2]
Reproduce test result comparison.

**Comment by eternalNight** [comment]
'lkp compare' gives statistics like the following. Statistics of this kind are seen in the performance regression reports.

```
d8ec26d7f8287f57  bfa76d49576599a4b9f9b7a71f
----------------  --------------------------
       228 ±244%      +0.0%        228 ±244%  hackbench/50%-threads-socket/localhost
       228            +0.0%        228        GEO-MEAN latency_stats.hits.......
```

The command to generate the statistics is

```
# lkp compare -a d8ec26d7f8287f57  bfa76d49576599a4b9f9b7a71f
```

where d8ec26d7f8287f57 and bfa76d49576599a4b9f9b7a71f are both git commit hashes. The following requirements must be met.
- The linux git repo is found at /c/repo/linux. Alternatively, one can change the directory by exporting the environment variable GIT_WORK_TREE or LINUX_GIT or change the default path hardcoded on line 6 in lib/lkp_git.rb.
- Some tests must be run using 'lkp run'. By default, the result directory can be found under the directory /result/{testcase}/{test params}/{test box}/{rootfs}/{kconfig}/{compiler} with the commit hash as its name (d8ec26d7f8287f57 and bfa76d49576599a4b9f9b7a71f in the above case). The above path should also be listed in some files under /lkp/paths/.

For a simple test, go through the following steps:
- use 'lkp run' to run a test
- go to the directory /result/{testcase}/{test params}/{test box}/{rootfs}/{kconfig}/{compiler} and rename the only directory to a commit hash available in Linux git (e.g. bfa76d49576599a4b9f9b7a71f)
- make a copy of the entire directory bfa76d49576599a4b9f9b7a71f and rename the copy to another commit hash (e.g. d8ec26d7f8287f57)
- go to /lkp/paths/ and save the paths to the above directories (something like /result/{testcase}/{test params}/{test box}/{rootfs}/{kconfig}/{compiler}/<commit hash>/0) to a file.
- make the directory /c/repo/ and clone the Linux git repo under it.
- comment out line 185 in sbin/compare and remove "tag || " on line 186
- comment out some "next unless ..." in the function __get_changed_stats() in lib/stats.rb
- run 'lkp compare -a d8ec26d7f8287f57 bfa76d49576599a4b9f9b7a71f ' as root

**Comment by chyyuu** [comment]
Can we repeat your progress?

**Comment by elliott10** [comment]
I followed the above steps, but I just got a message "tests: 1".

![Uploading lkp_compare.png…]()

**Comment by eternalNight** [comment]
Have you "commented out some "next unless ..." in the function __get_changed_stats() in lib/stats.rb"?  These statements are used to filter out statistics with no significant changes. I removed line 442-444, 465-467 and 498-500 in my case.

**Comment by elliott10** [comment]
I still can't get the Statistics of the performance regression reports.
Still got message:  tests: 1

**Comment by eternalNight** [comment]
Do you have a file called stats.json in your 'lkp run' result? Is there any data in it?

**Comment by elliott10** [comment]
Yes, stats.json file in the result directory.

The file content:
{
"uptime.boot": 24693.39,
"uptime.idle": 185332.03,
"interrupts.CPU0.0:IO-APIC-edge.timer": 0,
"interrupts.0:IO-APIC-edge.timer": 0,
"interrupts.CPU0.1:IO-APIC-edge.i8042": 0,
"interrupts.CPU1.1:IO-APIC-edge.i8042": 0,
......

"meminfo.Hugepagesize": 2048,
"meminfo.DirectMap4k": 71668,
 "meminfo.DirectMap2M": 33482752
 }

**Comment by elliott10** [comment]
Thanks for your help ! It works now.

lkp compare /path/to/result/0 /path/to/result/1
03891f9c853d5c44  47c62e4be78303ef52ffa81340  testcase/testparams/testbox

---

```
     %stddev     %change         %stddev
         \          |                \  
    71            +0.0%         71        ebizzy/200%-100x-10s/chy-KVM
    71            +0.0%         71        GEO-MEAN vmstat.cpu.sy
```

**Comment by dc3671** [comment]
Add some explanation from @eternalNight : 
@elliott10 's result of `tests: 1` only is because of the equivalence of two commits with just hashcode's difference.
The last command without `-a` only compared 0 & 1 these two tests results. If want more comparison, need to try `lkp compare -a d8ec26d7f8287f57 bfa76d49576599a4b9f9b7a71f` with different commit.

**Comment by eternalNight** [comment]
@elliott10 I think the problem you have encountered is that 'lkp compare -a' requires at least 3 runs in each result root. So simply repeat the jobs for some more times.
