### ISSUE TITLE
Generate shell scripts for in-VM tests from yaml descriptions

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#3]

**Comment by eternalNight** [comment]
The shell scripts are generated from yaml job descriptions which have additional fields added. To reproduce the complete analysis from scratch, we need to know what are the key fields in the job descriptions and how to fill them.

**Comment by dc3671** [comment]
Chose the benchmark `thrulay` to continue with the `.sh` reproduce work. (See report.md)

**Comment by dc3671** [comment]
Almost completed this work on `nbench`. Finished testing `lkp run` and need to continue with `lkp qemu`.
