### ISSUE TITLE
Build cgz files required for in-VM tests from scratch

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#4]

**Comment by eternalNight** [comment]
To build the final initrd for the VM, we need the following ingredients, mostin cgz (i.e. .cpio.gz) format.
- vmlinuz image (the field 'kernel' in yaml)
- modules of the kernel (the field 'modules_initrd' in yaml)
- A rootfs of a general-purpose distribution. (the field 'initrd' in yaml)
- LKP source (packed by the script, the field 'lkp_initrd' in yaml)
- Some benchmarks (can be packed by 'lkp pack'. The field 'bm_initrd' in yaml)

It looks like the ingredients can all be packed by ourselves from scratch.

**Comment by elliott10** [comment]
lkp-tests/sbin/pack can generate .cgz(default) or .deb(-d option) format package.

**Comment by dc3671** [comment]
@elliott10 could you give more details about the command?

**Comment by elliott10** [comment]
when install benchmarks, "pack" works.
when run "lkp qemu", "pack" create lkp-$arch.cgz for lkp_initrd.

**Comment by dc3671** [comment]
Three kinds of `.cgz` file need generated, (see [report](https://github.com/openthos/lkp-analysis/blob/master/report.md)):
- module.cgz/vmlinuz.cgz/linux-headers.cgz(from linux kernel)
- benchmark.cgz(need to write script program)
- monitors.cgz(lkp automatically)

`benchmark.cgz`'s problem is now mostly completed, using `lkp pack` with proper `pack/*` script file.

`.cgz` from kernel need generated from @elliott10 . consider using `kernelci`.

**Comment by dc3671** [comment]
Using `kernelci` and automatically compiling it can get `vmlinuz` file. `module.cgz` includes some library file, depends on which benchmark is included.
