### ISSUE TITLE
Launch a specific test in VM instead of being trapped by the user/passwd prompt

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#5]

**Comment by eternalNight** [comment]
To start a test, the following directories and files should exist in addition to the initrd ingredients.
- mkdir -p $LKP_SRC/rootfs/addon/root/.ssh
- mkdir -p $LKP_SRC/rootfs/addon/etc/ssh
- touch $LKP_SRC/rootfs/addon/etc/ssh/ssh_config
- An executable bash file at /lkp/scheduled/lkp-nex04/unit_ebizzy-performance-200%-100x-10s-x86_64-rhel-BASE-c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b-20150830-10493-9a909m-0.sh (use ebizzy-test.sh in our lkp-test git repo)

If the VM cannot get an IP address via DHCP, replace "ip=dhcp" at line 183 in lkp-exec/qemu to with "ip=10.0.2.15".

In a successful run, the user/passwd prompt will still be shown while the benchmark is running in the background. Use top to see if the VM is busy. The results can be found under /tmp/vm_test_result.

**Comment by chyyuu** [comment]
I hope to repeat your work!

**Comment by eternalNight** [comment]
Simply follow the above steps in Luoyuan's lkp-test repo, Please let me know if any strange thing occur.

**Comment by elliott10** [comment]
I have got the right output in /tmp/vm_test_result.
