### ISSUE TITLE
Collect results of in-VM tests

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#6]

**Comment by eternalNight** [comment]
After a successful run of 'lkp qemu', the results can be found under /tmp/vm_test_result by default.

The system in the VM writes these results to a shared folder which is passed to it as a fsdev (see the complete qemu command for details).

**Comment by chyyuu** [comment]
tell us how to repeat, please.

**Comment by elliott10** [comment]
I had a successful run of 'lkp qemu'.

Exec command:
qemu-system-x86_64 -vnc localhost:5 -serial stdio -fsdev local,id=test_dev,path=/tmp/vm_test_result/ebizzy-2016-01-13-15:46:39,security_model=none -device virtio-9p-pci,fsdev=test_dev,mount_tag=9p/virtfs_mount -kernel /tmp/lkp-qemu-downloads/pkg/linux/x86_64-rhel/gcc-4.9/c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b/vmlinuz-4.2.0-rc8 -append root=/dev/ram0 user=lkp job=/lkp/scheduled/lkp-nex04/unit_ebizzy-performance-200%-100x-10s-x86_64-rhel-BASE-c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b-20150830-10493-9a909m-0.yaml ARCH=x86_64 kconfig=x86_64-rhel branch=pm/linux-next commit=c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b BOOT_IMAGE=/pkg/linux/x86_64-rhel/gcc-4.9/c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b/vmlinuz-4.2.0-rc8 max_uptime=3319 RESULT_ROOT=/result/ebizzy/performance-200%-100x-10s/lkp-nex04/debian-x86_64-2015-02-07.cgz/x86_64-rhel/gcc-4.9/c13dcf9f2d6f5f06ef1bf79ec456df614c5e058b/0 LKP_SERVER=inn   earlyprintk=ttyS0,115200 systemd.log_level=err debug apic=debug sysrq_always_enabled rcupdate.rcu_cpu_stall_timeout=100 panic=-1 softlockup_panic=1 nmi_watchdog=panic oops=panic load_ramdisk=2 prompt_ramdisk=0 console=ttyS0,115200 console=tty0 vga=normal  rw  ip=10.0.2.15 result_service=9p/virtfs_mount -initrd /tmp/initrd-31535 -smp 2 -m 2048M -no-reboot -watchdog i6300esb -rtc base=localtime -device e1000,netdev=net0 -netdev user,id=net0 -drive file=/tmp/vdisk-root/disk0-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk1-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk2-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk3-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk4-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk5-lkp-nex04,media=disk,if=virtio -drive file=/tmp/vdisk-root/disk6-lkp-nex04,media=disk,if=virtio
