### ISSUE TITLE
Setup kernel-ci

### ISSUE THREAD

**Issue by eternalNight** [openthos/kis-analysis#7]
Setup kernel-ci and see if the framework is suitable for compile/boot tests for any project using git.

**Comment by elliott10** [comment]
buildroot -- To generate cross-compilation, kernel, bootloader, root filesystem, etc.
kernel-bugs -- Record Linux kernel bug to a text file.
kernelci-stable-reports -- For parsing email subjects, and send message.(still no code)
lava-kernel-tests -- Linux Kernel Tests for LAVA. Files "*.yaml" define the test configuration.
lava-ci -- some python script parse and run LAVA jobs. (don't know how to use it correctly.)
kernelci-frontend -- Data visualization dashboard for the kernelci-backend. It will bind to localhost:5000
kernelci-backend -- (I got some error.)

**Comment by chyyuu** [comment]
@elliott10 Can we run kernel-ci now?

**Comment by elliott10** [comment]
After requirement is installed,
kernelci-frontend server will bind to  port 5000,
kernelci-backend server will bind to  port 8888.

It can work normally, but I don't know how to use it correctly .

**Comment by dc3671** [comment]
Xiao Luoyuan has finished this work and can compile kernel into vmlinuz file.
